edgexfoundry/edgex-taf

TAF/testCaseModules/keywords/coreDataAPI.robot
docs/edgex-taf.rst

TAF needs to fetch the newest reading to verify the write command execution is correct.
Fix #44

Query readings by device name to fetch latest reading

---

TAF/testCaseModules/keywords/coreDataAPI.robot
TAF/testCaseModules/keywords/coreMetadataAPI.robot
TAF/testScenarios/functionalTest/core-data/UC_readings/add_reading.robot
TAF/testScenarios/functionalTest/core-data/UC_readings/query_reading.robot
docs/edgex-taf.rst

Fix #17 
Add test cases:
- Fail to add reading to core data srevice when the config MetaDataCheck set to true
- Success to add reading to core data srevice when the config MetaDataCheck set to true

Create test cases for adding reading

---

TAF/config/device-modbus/create_autoevent_device.json
TAF/config/device-modbus/create_disabled_device.json
TAF/config/device-modbus/create_locked_device.json
TAF/utils/scripts/docker/device-service.yaml

Create device and protocol point to modbus simulator container, not docker host.
fix #72

Fix modbus simulator error

---

.gitignore
TAF/utils/scripts/docker/deploy-edgex.sh
TAF/utils/scripts/docker/get-compose-file-backward.sh
TAF/utils/scripts/docker/get-compose-file.sh

Fix https://github.com/edgexfoundry/edgex-taf/issues/69
- add the missing ${BACKWARD} in docker-compose.yaml
- update scripts to get fuji compose file correctly for backward testing

Update scripts for taf-pipeline backward testing

---

TAF/testScenarios/integrationTest/UC_device_service/device_service.robot

1. To test all device profiles are created or not.
2. To test get or put command is executed correctly.
3. To test device events are received correctly.
Fix #59

Add robot file to create testcase for device-service

---

TAF/config/device-virtual/fuji/configuration.toml
TAF/utils/scripts/docker/docker-compose-device-service.yaml
TAF/utils/scripts/docker/get-compose-file-backward.sh
TAF/utils/scripts/docker/get-compose-file.sh

1. Update docker-compose to support both release, fuji and geneva.
2. Create a new configuration.toml for fuji release. 

Support device service for fuji release

---

TAF/utils/scripts/docker/get-compose-file.sh

Change portainer to device-virtual as keyword to append end to end docker-compose file.
Fix #81 

Use device-virtual as keyword to append app-service

---

TAF/utils/scripts/docker/deploy-edgex.sh
TAF/utils/src/setup/edgex.py

Based on developer-script [PR #271](https://github.com/edgexfoundry/developer-scripts/pull/271) to remove support logging startup.

remove logging service

---

TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot

1. clean_up_events_and_readings.robot: Call delete events/readings API to clean up events/readings.
2. clean_up_logging.robot: Call delete log API to delete log by parameter.
fix #55

Add robot file for support-scheduler

---

TAF/utils/scripts/docker/get-compose-file-backward.sh
TAF/utils/scripts/docker/sync-nightly-build.sh

Just fix the links to properly point to nightly-build compose files in master and not Lenny's branch

fix: Fixed links to nightly-build compose files to point to edgexfoundry master

---

TAF/testCaseModules/keywords/commonKeywords.robot
TAF/testCaseModules/keywords/coreDataAPI.robot
TAF/testScenarios/functionalTest/core-data/UC_readings/add_reading.robot
TAF/testScenarios/functionalTest/core-data/UC_readings/query_reading.robot
TAF/testScenarios/functionalTest/device-service/common/3_device_profile/3_device_profile.robot
TAF/testScenarios/functionalTest/device-service/common/5_query_commands/5_query_commands.robot
TAF/testScenarios/functionalTest/device-service/common/7_actuation_commands/7_actuation_commands.robot
TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot

Update the following keyword.
- For loop header ':FOR' is deprecated to use 'FOR' instead
- Marking for loop body with '\\' is deprecated. Remove markers and use 'END' instead.
Fix #134

For loop header ':FOR' is deprecated to use 'FOR' instead

---

TAF/utils/scripts/docker/docker-compose-device-service.yaml

Daily test failed because of missing environment variables "CLIENTS_DATA_HOST". Added all of required variables for device-services. 

Add common environment variables to device-services

---

TAF/config/performance-metrics/configuration.py
TAF/testCaseModules/keywords/performance-metrics-collection/PerformanceSummaryReports.py
TAF/testCaseModules/keywords/performance-metrics-collection/RetrieveFootprint.py
TAF/testCaseModules/keywords/performance-metrics-collection/RetrieveResourceUsage.py
TAF/testCaseModules/keywords/performance-metrics-collection/StartupTimeHandler.py
TAF/testScenarios/performanceTest/performance-metrics-collection/2_service_startup_time/service_startup_time.robot
TAF/testScenarios/performanceTest/performance-metrics-collection/3_resource_usage_with_autoevent/resource_usage_with_autoevent.robot
TAF/testScenarios/performanceTest/performance-metrics-collection/9_summary_reports/summary_reports.robot
TAF/utils/scripts/docker/deploy-edgex.sh

1. Add config variable to report.
2. Start consul first before starting all edgex services.
3. Fix report fails, if the running test of startup time fails.

Add parameter to report and fix service startup fail

---

TAF/testCaseModules/keywords/performance-metrics-collection/EventExportedTime.py
TAF/testCaseModules/keywords/performance-metrics-collection/PerformanceSummaryReports.py
TAF/testCaseModules/keywords/performance-metrics-collection/RetrieveSystemInfo.py
TAF/testScenarios/performanceTest/performance-metrics-collection/0_retrieve_system_info/retrieve_system_info.robot
TAF/testScenarios/performanceTest/performance-metrics-collection/1_retrieve_footprint/retrieve_footprint.robot
TAF/testScenarios/performanceTest/performance-metrics-collection/2_service_startup_time/service_startup_time.robot
TAF/testScenarios/performanceTest/performance-metrics-collection/3_resource_usage_with_autoevent/resource_usage_with_autoevent.robot
TAF/testScenarios/performanceTest/performance-metrics-collection/4_ping_response_time/ping_response_time.robot
TAF/testScenarios/performanceTest/performance-metrics-collection/5_event_exported_time/event_exported_time.robot
TAF/utils/scripts/docker/exec_performance_metrics.sh
TAF/utils/scripts/docker/get-compose-file-perfermance.sh

- Fix report didn't generate when data fails to compare with the threshold.
- Add error log if events didn't export.
Fix #179 

Fix report didn't generate when data fails to compare with threshold

---

TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot

update for https://github.com/edgexfoundry/edgex-taf/issues/155 based on the change https://github.com/edgexfoundry/app-functions-sdk-go/pull/497:
POST secrets without path returns status code 400

Update app-service secrets V2 API testcases

---

TAF/utils/scripts/docker/docker-compose-device-service.yaml
TAF/utils/scripts/docker/docker-compose-end-to-end.yaml
TAF/utils/scripts/docker/get-compose-file.sh
TAF/utils/scripts/docker/sync-nightly-build.sh

1. Adding the SHA1 field for downloading compose files from developer-script.
2. Based on the developer-script compose file to update the port number.
3. Add depend_on on all app-service services.
Fix #191 

Add new variable SHA1 for smoke testing

---

TAF/testScenarios/functionalTest/V2-API/core-metadata/device/DELETE.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Positive-II.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Positive.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/device/PATCH-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/device/PATCH-Positive.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/device/POST-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/device/POST-Positive.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Positive.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Positive-II.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Positive.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative-UploadFile.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Positive.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/DELETE-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/DELETE-Positive.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/GET-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/GET-Positive.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/PATCH-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/PATCH-Positive.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/info/GET.robot

Contain the following test cases.
- Device
- Device Profile without POST Method.
- Device Service without POST Method.
POST method for Device Profile and Device Service is in #189.
Fix #106 

Add core-metadata test cases

---

TAF/utils/scripts/docker/get-compose-file-perfermance.sh

Add argument value "master" on get-compose-file-performance.sh file.
Fix #202 

Use master for USE_SHA1 argument when executing performance metrics collection

---

TAF/testCaseModules/keywords/core-data/coreDataAPI.robot
TAF/testData/core-data/readings_data.json
TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-negative.robot
TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot
TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-negative.robot

Fix https://github.com/edgexfoundry/edgex-taf/issues/199
1. change origin to nanosecond
2. change floatEncoding to eNotation in readings_data.json
3. add content-type check to post-negative
4. get event by id positive and negative testcases
5. get event count testcases

Implement data GET event by id and event count V2 tests

---

TAF/testCaseModules/keywords/common/commonKeywords.robot

The keyword of `Delete device profile by name  ${profile name}` put on suite level, not test level, so change the used keyword from `set test variable` to `set suite variable`.

Change test variable to suite variable

---

TAF/utils/scripts/docker/get-compose-file-backward.sh

Change the filename in get-compose-file-backward.sh from `docker-compose-nexus-base.yml` to `docker-compose-base.yml`.
Fix #212 

Change the nightly build filename in get-compose-file-backward.sh

---

TAF/utils/scripts/docker/get-compose-file-backward.sh

The base compose file that is being pulled has move. This updates the URL used to pull the compose file
closes: #215

refactor: Adjust URL path to base compose file now under compose-builder

---

TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Positive-II.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/device/PATCH-Negative-II.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/device/PATCH-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/device/PATCH-Positive.robot

1. unset ${index} to empty
2. use Force Tages instead of Default Tags

Fix SmokeTest failures and use Force Tags

---

TAF/utils/scripts/docker/arm64.env
TAF/utils/scripts/docker/get-compose-file-backward.sh
TAF/utils/scripts/docker/get-compose-file-perfermance.sh
TAF/utils/scripts/docker/get-compose-file.sh
TAF/utils/scripts/docker/sync-nightly-build.sh
TAF/utils/scripts/docker/x86_64.env

Because the 1.3.0 is tagged, revert the change on PR #229.

Revert "Change image url to use dockerhub hanoi release"

---

TAF/testCaseModules/keywords/core-data/coreDataAPI.robot
TAF/testData/core-data/event_data.json
TAF/testData/core-data/readings_data.json
TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-negative.robot
TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-positive.robot

fix #234 
1. repalace name with resourceName and add profileName in reading data
2. remove labels in reading data
3. add profileName in event data
3. remove reading negative testcase: no floatEncoding

Update core-data V2 tests to use resourceName and profileName

---

TAF/utils/scripts/docker/docker-compose-end-to-end.yaml

Use MQTTSecretSend instead of MQTTSend for app-service-mqtt-export

Use MQTTSecretSend instead of MQTTSend for app-service-mqtt-export

---

TAF/utils/scripts/docker/docker-compose-end-to-end.yaml

Remove the RootCaCertPath from environments, becuase starting app-service with http-export-secrets still uses the RootCaCertPath.
Fix #250 

Update secure app-service to not override RootCaCertPath and Protocol

---

TAF/testData/core-data/readings_data.json
TAF/testData/core-metadata/deviceprofile/Test-Profile-1.yaml
TAF/testData/core-metadata/deviceprofile/Test-Profile-2.yaml
TAF/testData/core-metadata/deviceprofile/Test-Profile-3.yaml
TAF/testData/core-metadata/deviceprofile/Test-Profile-4.yaml
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Positive.robot
TAF/utils/scripts/docker/deploy-edgex.sh

Fix https://github.com/edgexfoundry/edgex-taf/issues/252
1. update all deviceprofile properties type to camel case format for consistency
2. update reading resourceName to use hyphen instead of space
3. replace security-secrets-setup with security-bootstrapper and remove kong-migrations in deploy-edgex.sh

Update deviceprofile and reading test data

---

TAF/utils/scripts/docker/docker-compose-device-service.yaml
TAF/utils/scripts/docker/docker-compose-end-to-end.yaml

Fix https://github.com/edgexfoundry/edgex-taf/issues/254
1. Remove secret store exclusive configuration from app-service-http-export-secrets
2. Update secret store path and token file to fix secrets V2 API Jenkins failures
3. Update yaml files to use uppercase environment overrides 

Update app service yaml file and use uppercase environment overrides

---

TAF/testCaseModules/keywords/performance-metrics-collection/EventExportedTime.py
TAF/testScenarios/performanceTest/performance-metrics-collection/5_event_exported_time/event_exported_time.robot
TAF/utils/src/setup/mqtt-subscriber.py

Retrieve the timestamp while receiving the event on the subscriber, and use it instead of push time.
Fix #260 

Use received timestamp instead of pushed timestamp

---

TAF/testCaseModules/keywords/performance-metrics-collection/EventExportedTime.py
TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
TAF/utils/src/setup/mqtt-subscriber.py

1. Add argument while running mqtt-subscriber to use different loop function.
2. Modify the function when reading the subscriber log.

Update mqtt subscriber to not disconnect after receiving a message

---

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot
TAF/testScenarios/functionalTest/V2-API/app-service/info/GET.robot
TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot
TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot
TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot
TAF/utils/scripts/docker/api-gateway-token.sh
TAF/utils/scripts/docker/deploy-edgex.sh

Based on [developer-script #372](https://github.com/edgexfoundry/developer-scripts/pull/372) to update scripts.
1. Modify service name from `edgex-proxy` to `proxy-setup` and `vault-worker` to `secretstore-setup`.
2. Modify `appservice-http-export-secrets` to `app-service-http-export-secrets`  for SECRETSTORE Path.
Fix #271 

Update edgex-proxy and vault-worker service name

---

TAF/testCaseModules/keywords/performance-metrics-collection/EventExportedTime.py

Change key from device to deviceName for getting event exported time
Fix #288 

Change key from device to deviceName for getting event exported time

---

TAF/testCaseModules/keywords/common/commonKeywords.robot
TAF/testCaseModules/keywords/core-data/coreDataAPI.robot
TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-positive.robot
TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-negative.robot
TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot
TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-negative.robot
TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-positive.robot

Replace milliseconds with nanoseconds when querying event/reading by start/end time
Fix #348

Replace milliseconds with nanoseconds

---

TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-positive.robot

The unit of age is by nanosecond. If the calculating time is too close, that is easy to delete the event that we want to keep.
Add waiting time between the age calculated value to avoid the age calculating incorrectly.
#348

Add waiting time to avoid the age calculating incorrectly for the test of delete event by age API

---

TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/PATCH-Negative.robot

Changing the returned status code to 207 when updating subscription with empty labels and categories
Fix #356 

Changing the returned status code to 207 when updating subscription with empty labels and categories

---

TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot
TAF/utils/scripts/docker/deploy-edgex.sh

Use app-service-http-export instead of app-service-http-export-secure.
Fix #365 

Use app-service-http-export instead of app-service-http-export-secure

---

TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/PATCH-Negative.robot

1. Request body contains empty labels and categories should return 400.
2. Creating subscription without labels, then set categories to empty when updating subscription should return 207 with 400 on returned response json body.
Fix #367

Modify subscription test scenarios for updating labels and categories

---

TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/GET.robot

Reverts edgexfoundry/edgex-taf#404, because it blocked [edgexfoundry/edgex-compose #83 ](https://github.com/edgexfoundry/edgex-compose/pull/83)

Revert "Add scheduler tests to SmokeTest for kong issue"

---

TAF/config/global_variables.py
TAF/testCaseModules/keywords/common/commonKeywords.robot
TAF/testScenarios/functionalTest/V2-API/app-service/info/GET.robot
TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot
TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot
TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot
docs/run-tests-on-local.md

1. Update functional-test notices for launching edgex without compose file.
2. Add a variable of app service port to global_variables.py.
Fix #389 

Update functional-test notices for launching edgex without compose file

---

TAF/testData/support-notifications/subscription_data.json
TAF/testData/support-scheduler/interval_action.json
TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/PATCH-Negative.robot
TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/POST.robot
TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/PATCH-Negative.robot
TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/POST-Negative.robot

Add adminState field into test data of intervalaction and subscription.
Fix #406 

Add adminState field into test data of intervalaction and subscription

---

TAF/testCaseModules/keywords/core-data/coreDataAPI.robot
TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
TAF/utils/scripts/docker/get-compose-file.sh

1. Stop app-service for scalability-test service.
2. Remove add proxy route for device-modbus, the fix moves to [edgexfoundry/edgex-compose #101](https://github.com/edgexfoundry/edgex-compose/pull/101).

Stop app-service for scalability-test service

---

TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/GET.robot
TAF/testScenarios/integrationTest/UC_kuiper/export_by_kuiper_rules.robot

Replace http with URI_SCHEME variable for kuiper url.
Add sleep time after restart service. 

Replace http with URI_SCHEME variable for kuiper url.

---

TAF/config/default/configuration.toml
TAF/config/modbus_scalability_test/configuration.toml

- go-mod-bootstrap has implemented the addition of prefix /v1/secret/edgex/ for the Path property of SecretStore config section, so we just use the service specific secret path in Toml files
- also retry related item in SecretStore config no longer needed and hence removed
Fix: #449
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>
@cherrycl , @cloudxxx8 , @lenny-intel

fix: Remove retry items of SecretStore config and update secret path

---

TAF/testCaseModules/keywords/common/commonKeywords.robot
TAF/testCaseModules/keywords/system-agent/systemAgentAPI.robot
TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/GET.robot
TAF/testScenarios/functionalTest/V2-API/system-agent/services/GET-Negative.robot
TAF/testScenarios/functionalTest/V2-API/system-agent/services/GET-Positive.robot
TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Negative.robot
TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Positive.robot
TAF/utils/scripts/docker/restart-services.sh

1. Remove success field validation in system tests
2. Waiting for 2s after restart services for kong cache issue.
Fix #461

Remove success field validation in system tests

---

TAF/testCaseModules/keywords/setup/edgex.py
TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot
TAF/testScenarios/functionalTest/V2-API/system-agent/services/GET-Negative.robot
TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Negative.robot
TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Positive.robot

- Add 'edgex-' prefix to app-service related containers.
- Change the test service for system-agent tests to avoid failure caused by previous tests.
Fix #480

fix: add 'edgex-' prefix to app-service related containers

---

TAF/testScenarios/performanceTest/performance-metrics-collection/2_service_startup_time/service_startup_time.robot

Increasing sleep time after start services for performance metrics

fix: increasing sleep time after start services for performance metrics

---

TAF/testCaseModules/keywords/core-data/coreDataAPI.robot
TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-negative.robot
TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-positive.robot

feat: Implement tests for query readings by name and time range

---

TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot

After the change of [edgexfoundry/app-service-configurable PR#347](https://github.com/edgexfoundry/app-service-configurable/pull/347), [TriggerPost006](https://github.com/edgexfoundry/edgex-taf/blob/b20f26be9e550ed9362321b6c9b33ea464bdaf26/TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot#L60) is invalid for non-security test.

Set tag to skipped for aes related test

---

TAF/testScenarios/integrationTest/UC_app_service_configurable/external_mqtt_trigger.robot

1. Change subscriber keyword from a string to a word.
2. Sleep 1s to waiting for subscriber ready.
Fix #536 

fix: Change keyword when subscribe mqtt message

---

TAF/utils/scripts/snap/api-gateway-token.sh
TAF/utils/scripts/snap/deploy-device-service.sh
TAF/utils/scripts/snap/deploy-edgex.sh
TAF/utils/scripts/snap/deploy-services.sh
TAF/utils/scripts/snap/restart-services.sh
TAF/utils/scripts/snap/run-tests.sh
TAF/utils/scripts/snap/shutdown.sh
TAF/utils/scripts/snap/snap-taf-tests.sh
TAF/utils/scripts/snap/snap-utils.sh
TAF/utils/scripts/snap/stop-services.sh

This commits fixes a number of minor issues, so that more tests now pass when testing with snaps
- Changed logging to use stderr only instead of logger
- patched more docker-specific functionality in the robot and python files
- setting up correct modbus profiles
- using latest/edge instead of 2.0/edge
- installing the python3-is-python package
All the changes are snap-specific only. To run the tests with snaps do:
```
cd edgex-taf/TAF/utils/scripts/snap
sudo ./run-tests.sh -h # to print out help
sudo ./run-tests.sh -t all # to run all functional tests
sudo ./run-tests.sh -i  # to run integration tests
```
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

fix(snap): update snap test scripts

---

TAF/utils/scripts/snap/restart-services.sh
TAF/utils/scripts/snap/run-tests.sh
TAF/utils/scripts/snap/snap-taf-tests.sh

This commit fixes the remaining issues that prevent
support-notifications and support-scheduler tests from
passing when testing with snaps.
It also disables the system-agent tests.
Running all tests with
```
cd TAF/utils/scrips/snap
sudo ./run-tests.sh -t all
```
now results in all tests passing.
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

fix(snap): fix issues with snaps and functional tests

---

TAF/utils/scripts/snap/api-gateway-token.sh
TAF/utils/scripts/snap/restart-services.sh
TAF/utils/scripts/snap/run-tests.sh
TAF/utils/scripts/snap/snap-taf-tests.sh
TAF/utils/scripts/snap/snap-utils.sh
TAF/utils/scripts/snap/stop-services.sh

This commit updates the scripts for running TAF tests
with snaps, fixing a number of issues with running the
integration tests.
With this PR, all TAF integration tests should pass when using snaps.
Test using:
```
cd edgex-taf/TAF/utils/scripts/snap
sudo ./run-tests -i
```
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>

feat(snap): enable integration tests with snaps

---

TAF/utils/scripts/docker/exec_performance_metrics.sh
TAF/utils/scripts/docker/get-compose-file-perfermance.sh
TAF/utils/scripts/docker/get-compose-file.sh
TAF/utils/scripts/docker/run-tests.sh
docs/run-tests-on-local.md

path: edgex-taf/TAF/utils/scripts/docker
-revise arguments in run-tests.sh
-change value of ${USE_SHA1} to "jakarta" in files as shown below
get-compose-file-perfermance/exec_performance_metrics.sh/get-compose-file.sh
path: edgex-taf/TAF/docs
-update run-tests-on-local.md
fix #609

fix: Update script to pull the v2.1.x images

---

TAF/config/performance-metrics/configuration.py
TAF/testCaseModules/keywords/performance-metrics-collection/EventExportedTime.py

fix: Get correct event on performance metrics collection

---

TAF/testCaseModules/keywords/common/commonKeywords.robot
TAF/testCaseModules/keywords/device-sdk/deviceServiceAPI.robot
TAF/testScenarios/integrationTest/UC_device_service/messagebus_false.robot
TAF/testScenarios/integrationTest/UC_device_service/messagebus_true.robot
TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
TAF/testScenarios/integrationTest/UC_metrics/core_data_metrics_mqtt.robot
TAF/testScenarios/integrationTest/UC_metrics/core_data_metrics_redis.robot

Add tests for redis and mqtt both messagebus on separate file.
Fix #681

feat: Add core-data metrics test

---

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot
TAF/testCaseModules/keywords/common/commonKeywords.robot
TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot
TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot
TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Negative-Deviceresource.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Positive-Deviceresource.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Deviceresource.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Uploadfile.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-Deviceresource.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative-UploadFile.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Positive.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/info/GET.robot
TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Positive-II.robot
TAF/testScenarios/integrationTest/UC_device_service/device_configuration.robot
TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot
TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot

1. Implement tests for Units of Measure(UoM)
2. Remove tests on PATCH device resource, device resource can't update units.
3. Modify some keywords
Fix #684

feat: Implement tests for Units of Measure(UoM)

---

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Deviceresource.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Uploadfile.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative-UploadFile.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative.robot

fix: Update status code to 400 when sending device profile with invalid units

---

TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot

1. Add sleep time to wait mqtt subscriber process is ready
2. To fix StoreAndForward001 got error sometimes, it fails sometimes when running process is slowly
Fix #715 

fix: Add sleep time to wait mqtt subscriber process is ready

---

TAF/testScenarios/integrationTest/UC_system_events/metadata_system_events_mqtt.robot

Integration test fails after #720 is merged, so adding Setup Suite to get token and pass the test.
fix #695

fix: add Setup Suite to get token

---

TAF/testCaseModules/keywords/common/commonKeywords.robot
TAF/testCaseModules/keywords/device-sdk/deviceServiceAPI.robot
TAF/testScenarios/integrationTest/UC_device_service/messagebus_false.robot
TAF/testScenarios/integrationTest/UC_device_service/messagebus_true.robot
TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
TAF/testScenarios/integrationTest/UC_kuiper/export_by_kuiper_rules.robot
TAF/utils/scripts/docker/get-compose-file-backward.sh
TAF/utils/scripts/docker/get-compose-file.sh

Fix #730
1. Update backward compose file to use external MQTT broker
2. Adjust some tests to avoid test failed on backward compatibility test sometimes
3. Dump service logs for debug.

fix: Update backward compose file to use external MQTT broker

---

TAF/testCaseModules/keywords/core-command/externalSystem.robot
TAF/testCaseModules/keywords/device-sdk/deviceServiceAPI.robot
TAF/testData/core-metadata/device_protocol.json
TAF/testScenarios/functionalTest/V2-API/core-command/device/GET-Negative.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/GET-Positive.robot
TAF/testScenarios/integrationTest/UC_north_south_messaging/GET-Negative.robot

Implment north-south messaging negative test for device-onvif-camera
The case was skipped on #728

fix: Implment north-south messaging negative test for device-onvif-camera

---

TAF/config/global_variables.py
TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot
TAF/testCaseModules/keywords/common/metrics.robot
TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot
TAF/testCaseModules/keywords/system-agent/systemAgentAPI.robot
TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot
TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-negative.robot
TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot
TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Positive-II.robot
TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/POST-Positive.robot
TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Negative.robot
TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Positive.robot
TAF/testScenarios/integrationTest/UC_device_service/device_configuration.robot
TAF/testScenarios/integrationTest/UC_device_service/messagebus_false.robot
TAF/testScenarios/integrationTest/UC_device_service/messagebus_true.robot
TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
TAF/testScenarios/integrationTest/UC_metadata_notifications/metadata_notifications.robot
TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_mqtt.robot
TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_redis.robot
TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot
TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot
TAF/testScenarios/scalabilityTest/modbus/modbus.robot

closes #743
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
This PR is dependent on the following PRs being merged:
- https://github.com/edgexfoundry/go-mod-core-contracts/pull/776
- https://github.com/edgexfoundry/go-mod-bootstrap/pull/401
- https://github.com/edgexfoundry/edgex-go/pull/4243
- https://github.com/edgexfoundry/app-functions-sdk-go/pull/1238
And the dependencies propagated to:
- Device SDK
- ASC
- Device Services.

refactor: Change to use new flattened Consul paths

---

TAF/testScenarios/integrationTest/UC_metadata_notifications/metadata_notifications.robot

fix: typo for setting CONSUL_CONFIG_BASE_ENDPOINT variable

---

TAF/testCaseModules/keywords/common/commonKeywords.robot
TAF/testScenarios/functionalTest/V2-API/app-service/info/GET.robot
TAF/testScenarios/functionalTest/V2-API/core-command/info/GET.robot
TAF/testScenarios/functionalTest/V2-API/core-data/info/GET.robot
TAF/testScenarios/functionalTest/V2-API/core-metadata/info/GET.robot
TAF/testScenarios/functionalTest/V2-API/support-notifications/info/GET.robot
TAF/testScenarios/functionalTest/V2-API/support-scheduler/info/GET.robot
TAF/testScenarios/functionalTest/device-service/common/info/GET.robot

This enpoint is being removed in https://github.com/edgexfoundry/edgex-go/pull/4311 and future PRs for App and Device SDKs
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>

refactor: Remove tests for /metrics endpoint

---

TAF/utils/scripts/docker/deploy-edgex.sh
docs/run-tests-on-local.md

Update script to override profileDir path according to the common-config feature Close #779
Signed-off-by: bruce <weichou1229@gmail.com>
Run `python3 -m TUC --exclude Skipped --include deploy-base-service -u deploy.robot -p default` and check whether the config is changed.

fix: Update script to override profileDir path

---

TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot

fix: Set timeout for Run Process keyword to fix timeout issue when security enabled

---

TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot
TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/POST-Positive.robot
TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot
TAF/testScenarios/integrationTest/UC_device_service/new_source_commands.robot
TAF/testScenarios/integrationTest/UC_device_service/usemessagebus.robot
TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot
TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot

Closes #809
Also fixed: 
1. Update the service name for the change on [edgex-compose PR #361](https://github.com/edgexfoundry/edgex-compose/pull/361)
2. Delete events on suite teardown to avoid the error on next suite

refactor: Add AuthMethod on intervalaction API when security enabled

---

TAF/testCaseModules/keywords/common/commonKeywords.robot
TAF/testScenarios/functionalTest/API/core-command/device/GET-Negative.robot
TAF/testScenarios/integrationTest/UC_CORS_configuration/cors_configuration.robot
TAF/utils/scripts/docker/get-compose-file.sh

Closes #850 
Enable CORS configuration security test and remove invalid test `Enable CORS without Origin header` .

fix: Enable CORS configuration security test

---

TAF/testScenarios/functionalTest/API/support-scheduler/intervalaction/POST-Positive.robot
TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_redis.robot
TAF/testScenarios/integrationTest/UC_retention/core_data_retention.robot
TAF/testScenarios/integrationTest/UC_retention/notifications_retention.robot

Closes #885 
- To fix failure tests for store and forward.
- Update the invalid parameter for retention tests
- Update script to avoid the related test of intervalaction and metrics tests got failure

fix: Update the timing of getting timestamp when query service log

---

TAF/utils/scripts/docker/shutdown.sh

Closes #890 
Lost shutdown script on PR #891 

fix: Add environment variable file while shutting down services

---

TAF/config/device-modbus/sample_profile.yaml
TAF/testScenarios/integrationTest/UC_device_service/device_configuration.robot

Closed #962 
Added integration test cases to verify bidirectional behavior of DataTransform when the shift field is set. The tests cover:
- RW (with shift) write + R (no shift) read → verify transform on write only
- W (no shift) write + RW (with shift) read → verify transform on read only
- One control case with DataTransform: false to ensure no transformation

feat: Implement bidirectional DataTransform integration tests with Modbus
