edgexfoundry/edgex-taf

updateme.sh
Signed-off-by: Vishwas SP <vishwasx.s.premachandra@intel.com>
=> Update on chmod for the script

TAF/testCaseApps/keywords/commonKeywords.robot, TAF/testCaseApps/keywords/coreCommandAPI.robot, TAF/testCaseApps/keywords/coreDataAPI.robot, TAF/testCaseApps/keywords/coreMetadataAPI.robot, TAF/testCaseApps/keywords/deviceServiceAPI.robot, TAF/testScenarios/4_device/4_device.robot, TAF/testScenarios/5_query_commands/5_query_commands.robot, TAF/testScenarios/6_scheduling/6_scheduling.robot, TAF/testScenarios/7_actuation_commands/7_actuation_commands.robot, TAF/testScenarios/8_metadata_updates/8_metadata_updates.robot
Changing set variable keywords to "set test variable" or "set suite variable", instead of "set environment variable.
Fix #23
=> Change set variable keywords

.gitmodules, TAF/utils/src/setup/consul.py, TAF/utils/src/setup/startup_checker.py
Fix #25 
1. Remove submodule 
2. add HttpConnTimeout to prevent http connection stuck.
=> Remove submodule and add HttpConnTimeout

TAF/testCaseApps/edgex_cli/Cli.py, TAF/testScenarios/00_command_line/00_command_line.robot
-Added TC for positive get profiles list
-Added TC for negative get profiles list
=> Added Example for testing edgex-cli

TAF/config/default/configuration.py, TAF/config/device-modbus/configuration.py, TAF/config/device-random/configuration.py, TAF/config/device-random/configuration.toml, TAF/config/device-random/docker/configuration.toml, TAF/config/device-random/sample_profile.yaml, TAF/config/device-virtual/configuration.py, TAF/testCaseModules/keywords/coreMetadataAPI.robot, TAF/testCaseModules/keywords/deviceServiceAPI.robot, TAF/testCaseModules/keywords/loggingAPI.robot, TAF/testScenarios/functionalTest/deploy-edgex.robot, TAF/testScenarios/functionalTest/device-service/common/3_device_profile/3_device_profile.robot, TAF/testScenarios/functionalTest/device-service/common/4_device/4_device.robot, TAF/testScenarios/functionalTest/device-service/common/5_query_commands/5_query_commands.robot, TAF/testScenarios/functionalTest/device-service/common/6_scheduling/6_scheduling.robot, TAF/testScenarios/functionalTest/device-service/common/7_actuation_commands/7_actuation_commands.robot, TAF/testScenarios/functionalTest/device-service/common/8_metadata_updates/8_metadata_updates.robot, TAF/testScenarios/functionalTest/edgex-cli/00_command_line/00_command_line.robot, TAF/testScenarios/integrationTest/1_service_operation/1_service_operation.robot, TAF/testScenarios/integrationTest/2_configuration_setting/2_configuration_setting.robot, TAF/utils/scripts/docker/docker-compose.yaml, docs/CH-Edgex-taf.rst
- Modify DEVICE_SERVICE_NAME and DEVICE_SERVICE_EDGEX_NAME to SERVICE_NAME
- Modify docker-compose file to match the SERVICE_NAME for deploying
=> Rename the field of configuration.py and fix test fail

TAF/testCaseModules/keywords/coreDataAPI.robot
- Query reading by device name instead of query all API
- Query the initial reading count and calculate expected reading count
Fix #36
=> Modify 6_scheduling test script to support C DS

TAF/testCaseModules/keywords/coreDataAPI.robot, TAF/utils/src/data/value_checker.py
Fix #40 
Fix schedule testing error and add eNotation parsing
=> Fix schedule testing error and add eNotation parsing

TAF/utils/src/data/value_checker.py
Fix #46 
Check the float value should smaller than the offset when compare to the expected value.
=> Check the float value should smaller than the offset

TAF/utils/scripts/docker/deploy-device-service-with-confdir-option.sh, TAF/utils/scripts/docker/deploy-device-service-with-profile-option.sh, TAF/utils/scripts/docker/deploy-device-service-with-registry-url.sh, TAF/utils/scripts/docker/deploy-device-service.sh, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/remove-services.sh, TAF/utils/scripts/docker/restart-services.sh, TAF/utils/scripts/docker/shutdown.sh, TAF/utils/scripts/docker/stop-services.sh
1. Set compose image to a variable
2. Get values of get-compose-file.sh from Jenkinsfile
fix #43
=> Set compose image to variable

TAF/testScenarios/functionalTest/support-notification/UC_notifications/notification.robot, TAF/testScenarios/functionalTest/support-notification/UC_subscription/subscriber.robot
1. notification.robot: Verify when updating devices will create a notification
2. subscriber.robot: Verify the transmission created when the label of notification has been subscribed.
=> Add robot files for support-notifications

TAF/utils/scripts/docker/deploy-edgex.sh
Start security services with sleep delay.
fix #64
=> Deploy security service when security enabled

TAF/utils/scripts/docker/deploy-edgex.sh
Start consul before startup core services
Fix #66
=> Start consul before startup core services

.gitignore, TAF/testScenarios/deploy-edgex-backward.robot, TAF/testScenarios/functionalTest/core-data/UC_readings/query_reading.robot, TAF/testScenarios/functionalTest/device-service/common/3_device_profile/3_device_profile.robot, TAF/testScenarios/functionalTest/device-service/common/4_device/4_device.robot, TAF/testScenarios/functionalTest/device-service/common/5_query_commands/5_query_commands.robot, TAF/testScenarios/functionalTest/device-service/common/6_scheduling/6_scheduling.robot, TAF/testScenarios/functionalTest/device-service/common/7_actuation_commands/7_actuation_commands.robot, TAF/testScenarios/functionalTest/device-service/common/8_metadata_updates/8_metadata_updates.robot, TAF/testScenarios/shutdown-backward.robot, TAF/utils/scripts/docker/deploy-device-service.sh, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/remove-services.sh, TAF/utils/scripts/docker/shutdown.sh, TAF/utils/src/setup/edgex.py
fix https://github.com/edgexfoundry/blackbox-testing/issues/264
=> Add core service compatibility deployment

TAF/testScenarios/integrationTest/UC_end_to_cloud/export_data_to_backend.robot
- Export data to HTTP Server
- Export data to MQTT Server
=> Add robot file to create testcase for exporting data to backend

TAF/utils/scripts/docker/arm64.env, TAF/utils/scripts/docker/x86_64.env
Change images that are put on nexus3.
Fix #70 
=> Using modbus simulator image on nexus3

TAF/config/device-modbus/create_device.json, TAF/utils/scripts/docker/device-service.yaml
Correct the mapping port on docker-compose file.
Fix #72 
=> Update modbus simulator mapping port to 1502

TAF/config/device-modbus/configuration.toml, TAF/config/device-modbus/docker/configuration.toml, TAF/config/device-virtual/configuration.toml, TAF/config/device-virtual/docker/configuration.toml, TAF/utils/scripts/docker/docker-compose-device-service.yaml
Updated configuration.toml and docker-compose file to support the latest sdk.
Fix #77
=> update configuration.toml and docker-compose file

TAF/utils/scripts/docker/deploy-edgex.sh
Add condition for starting database.
Fix #85 
=> Start Database when deploy edgex

TAF/utils/scripts/docker/get-compose-file.sh
Change the keyword using to append docker-compose file from device-random and device-virtual to ui.
Fix #89.
=> Change the keyword using to append docker-compose file

TAF/utils/scripts/docker/arm64.env, TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/x86_64.env
Get compose file from developer-script/release/geneva folder
=> update to use geneva compose file

TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file.sh
Change geneva compose file path to geneva/compose-files
Change keyword to "metadata:" which using append services.
Fix #112  
=> Change geneva compose file path

TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file.sh
1. Change geneva compose file location.
2. Change the keyword to "metadata:" which using append services.
=> [Master]Change geneva compose file location

TAF/utils/scripts/docker/docker-compose-device-service.yaml, TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file.sh
- Change keyword to append compose file.
- Fix issue for backward testing.
=> Change keyword to append compose file

TAF/testCaseModules/keywords/commonKeywords.robot, TAF/testCaseModules/keywords/coreDataAPI.robot, TAF/testCaseModules/keywords/supportSchedulerAPI.robot, TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot
- Scheduler001-Set scheduler for each 30s to clean up events
- Scheduler002-Set scheduler for each 60s to clean up events
Fix #55 
=> Implement support-scheduler tests

TAF/utils/src/setup/edgex.py, TAF/utils/src/setup/startup_checker.py
Add checker to verify device service startup
Fix #118.
=> Add checker to verify service startup

TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot
Change the order to delete data.
Fix #120
=> Change the order to delete data

TAF/utils/scripts/docker/deploy-device-service.sh, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/deploy-services.sh, TAF/utils/scripts/docker/remove-services.sh, TAF/utils/scripts/docker/restart-services.sh, TAF/utils/scripts/docker/shutdown.sh, TAF/utils/scripts/docker/stop-services.sh
Add --security-opt label:disable in docker run command.
Close #124 
=> Add --security-opt label:disable in docker run command

TAF/utils/scripts/docker/arm64.env, TAF/utils/scripts/docker/deploy-device-service.sh, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/deploy-services.sh, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/remove-services.sh, TAF/utils/scripts/docker/restart-services.sh, TAF/utils/scripts/docker/shutdown.sh, TAF/utils/scripts/docker/stop-services.sh, TAF/utils/scripts/docker/x86_64.env
1. Change image version to 1.2.1.
2. Add "--security-opt label:disable" to fix centos permission issue.
3. Change the sed keyword to "#  device-random:"
Close #127
=> Change geneva image to 1.2.1

TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file.sh
Update keyword for combine geneva docker-compose file
Fix #126 
=> Update keyword for combine geneva docker-compose file

.gitignore, TAF/utils/scripts/docker/common-taf.env, TAF/utils/scripts/docker/common.env, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/deploy-services.sh, TAF/utils/scripts/docker/docker-compose-device-service.yaml, TAF/utils/scripts/docker/docker-compose-end-to-end.yaml, TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/sync-nightly-build.sh
closes #122
Draft PR to get feedback and help.
@cloudxxx8 , @cherrycl 
get-compose-file.sh is working, but need help testing.
need help in get-compose-file-backward.sh with the `sed` commands.
Thanks!
=> refactor: Update scripts to handle change to multi-file compose files.

TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/sync-nightly-build.sh
Fix https://github.com/edgexfoundry/edgex-taf/issues/151
=> Update sync-nightly-build.sh ARG and rename compose file

TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot
=> Replace incorrect port when running UC_data_clean_up tests with security test

TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/PUT.robot, TAF/testScenarios/functionalTest/V2-API/core-data/info/GET-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-positive.robot
Fix https://github.com/edgexfoundry/edgex-taf/issues/99
Fix https://github.com/edgexfoundry/edgex-taf/issues/100
=> Create Core Data v2 API Functional Testcases

docs/edgex-taf.md
- Reorder the steps to Separate development and testing.
- Add step to describe how to change deploy type.
=> Separate development steps and testing steps on edgex-taf.md

TAF/config/performance-metrics/configuration.py, TAF/testCaseModules/keywords/common/value_checker.py, TAF/testCaseModules/keywords/performance-metrics-collection/RetrieveFootprint.py, TAF/testCaseModules/keywords/performance-metrics-collection/RetrieveResourceUsage.py, TAF/testCaseModules/keywords/performance-metrics-collection/data_utils.py, TAF/testScenarios/performanceTest/performance-metrics-collection/1_retrieve_footprint/retrieve_footprint.robot, TAF/testScenarios/performanceTest/performance-metrics-collection/3_resource_usage_with_autoevent/resource_usage_with_autoevent.robot
1. Correct name on retrieve footprint test.
2. Add test for retrieving CPU and memory usage.
Fix #141
=> Retrieve resource usage while sending autoevent

TAF/config/performance-metrics/configuration.py, TAF/testCaseModules/keywords/performance-metrics-collection/ServiceStartupTime.py, TAF/testCaseModules/keywords/performance-metrics-collection/StartupTimeHandler.py, TAF/testCaseModules/keywords/performance-metrics-collection/data_utils.py, TAF/testCaseModules/keywords/setup/startup_checker.py, TAF/testScenarios/performanceTest/performance-metrics-collection/2_service_startup_time/service_startup_time.robot
Add tests to retrieve all services startup time.
Fix #139
=> Retrieve Services Startup time

TAF/testCaseModules/keywords/performance-metrics-collection/PerformanceSummaryReports.py, TAF/testCaseModules/keywords/performance-metrics-collection/RetrieveResourceUsage.py, TAF/testScenarios/performanceTest/performance-metrics-collection/9_summary_reports/summary_reports.robot
Create a new test suite to show all of performance metrics data on the same tests.
Fix issue-140
=> Generate performance metrics report

TAF/testCaseModules/keywords/performance-metrics-collection/PerformanceSummaryReports.py, TAF/testCaseModules/keywords/performance-metrics-collection/ServiceStartupTime.py, TAF/testCaseModules/keywords/performance-metrics-collection/StartupTimeHandler.py, TAF/testCaseModules/keywords/performance-metrics-collection/data_utils.py, TAF/testScenarios/performanceTest/performance-metrics-collection/2_service_startup_time/service_startup_time.robot
=> Update startup time report to show aggregation values for all services

TAF/config/performance-metrics/configuration.py, TAF/testCaseModules/keywords/performance-metrics-collection/PerformanceSummaryReports.py, TAF/testCaseModules/keywords/performance-metrics-collection/PingResponse.py, TAF/testCaseModules/keywords/performance-metrics-collection/StartupTimeHandler.py, TAF/testScenarios/performanceTest/performance-metrics-collection/4_ping_response_time/ping_response_time.robot
=> Retrieve ping response time

TAF/config/performance-metrics/configuration.py, TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testCaseModules/keywords/performance-metrics-collection/EventExportedTime.py, TAF/testCaseModules/keywords/performance-metrics-collection/PerformanceSummaryReports.py, TAF/testCaseModules/keywords/performance-metrics-collection/PingResponse.py, TAF/testCaseModules/keywords/performance-metrics-collection/RetrieveFootprint.py, TAF/testCaseModules/keywords/performance-metrics-collection/RetrieveResourceUsage.py, TAF/testCaseModules/keywords/performance-metrics-collection/ServiceStartupTime.py, TAF/testCaseModules/keywords/performance-metrics-collection/StartupTimeHandler.py, TAF/testCaseModules/keywords/performance-metrics-collection/data_utils.py, TAF/testScenarios/performanceTest/performance-metrics-collection/2_service_startup_time/service_startup_time.robot, TAF/testScenarios/performanceTest/performance-metrics-collection/3_resource_usage_with_autoevent/resource_usage_with_autoevent.robot, TAF/testScenarios/performanceTest/performance-metrics-collection/4_ping_response_time/ping_response_time.robot, TAF/testScenarios/performanceTest/performance-metrics-collection/5_event_exported_time/event_exported_time.robot, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/exec_performance_metrics.sh, TAF/utils/scripts/docker/pull-images.sh, TAF/utils/scripts/docker/shutdown.sh
1. Retrieve events exported time
2. Create keyword for the same steps on ping response time test suite.
Fix #143
=> Retrieve events exported time

TAF/testScenarios/functionalTest/V2-API/app-service/info/GET.robot, TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST.robot
Fix https://github.com/edgexfoundry/edgex-taf/issues/155
=> Add App Service V2 Testcases

TAF/testScenarios/performanceTest/performance-metrics-collection/2_service_startup_time/service_startup_time.robot, TAF/utils/scripts/docker/restart-services.sh
=> Use restart services when measuring startup time without creating container

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot, TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testData/app-service/secrets_data.json, TAF/testData/app-service/trigger_data.json, TAF/testData/app-service/trigger_response_content.py, TAF/testScenarios/functionalTest/V2-API/app-service/info/GET.robot, TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot, TAF/testScenarios/functionalTest/core-data/UC_readings/add_reading.robot, TAF/utils/scripts/docker/docker-compose-end-to-end.yaml, TAF/utils/scripts/docker/get-compose-file.sh
Fix https://github.com/edgexfoundry/edgex-taf/issues/155
=> Implement app service V2 API test cases

TAF/testScenarios/functionalTest/V2-API/core-data/event/POST.robot
Fix https://github.com/edgexfoundry/edgex-taf/issues/184
=> Update core-data post event V2 API testcases

TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-positive.robot, TAF/testScenarios/functionalTest/device-service/common/3_device_profile/3_device_profile.robot, TAF/testScenarios/functionalTest/device-service/common/5_query_commands/5_query_commands.robot, TAF/testScenarios/functionalTest/device-service/common/7_actuation_commands/7_actuation_commands.robot, TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
=> Add "SmokeTest" tag for developer-script validation

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Uploadfile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/POST-Positive.robot
Create test cases for POST `device profile` and `device service`.
=> Create post device profile and device service test cases

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testScenarios/functionalTest/V2-API/app-service/info/GET.robot, TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/PUT.robot, TAF/testScenarios/functionalTest/V2-API/core-data/info/GET.robot, TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-positive.robot
Fix https://github.com/edgexfoundry/edgex-taf/issues/195
=> Add time limit keyword to V2 API testcases

TAF/utils/scripts/docker/get-compose-file-perfermance.sh
Arguments order incorrect that cause the incorrect filename.
=> Update arguments order when downloading compose file for performance

TAF/utils/scripts/docker/docker-compose-end-to-end.yaml
Generate docker-compose-mqtt.yaml got failure because the compose component order is incorrect.
=> Update end-to-end test yaml file for performance metrics collection

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/core-metadata/deviceprofile/Test-Profile-1.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-2.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-3.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-4.yaml, TAF/testData/core-metadata/deviceservice_data.json, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Uploadfile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/POST-Positive.robot, TAF/testScenarios/functionalTest/core-data/UC_readings/add_reading.robot, TAF/testScenarios/functionalTest/device-service/common/8_metadata_updates/8_metadata_updates.robot, TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
Fix: https://github.com/edgexfoundry/edgex-taf/issues/197
=> Implement metadata POST deviceprofile and deviceservice V2 tests

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Uploadfile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative-UploadFile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/DELETE-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/DELETE-Positive.robot
Fix https://github.com/edgexfoundry/edgex-taf/issues/201
=> Implement metadata DELETE/PUT deviceprofile and DELETE deviceservice V2 API tests

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Uploadfile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative-UploadFile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/PATCH-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/PATCH-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/POST-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/info/GET.robot
Fix https://github.com/edgexfoundry/edgex-taf/issues/209
Also correct filenames in PUT-Negative-UploadFile.robot
=> Implement metadata GET deviceservice/deviceprofile and PATCH deviceservice

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/core-metadata/V2-device/auto_events_data.json, TAF/testData/core-metadata/V2-device/device_data.json, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/POST-Negative-ll.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/POST-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/DELETE-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/DELETE-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/GET-Positive.robot
Fix https://github.com/edgexfoundry/edgex-taf/issues/214
testcases: post device, delete device by id, delete device by name, get all devices, get device by name, get device by id, check device by name, check device by id
=> Implement core-metadata POST/DELETE/GET device

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Positive-II.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/PATCH-Negative-II.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/PATCH-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/PATCH-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/POST-Negative-II.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/POST-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/DELETE-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/PATCH-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/PATCH-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/POST-Positive.robot
Fix https://github.com/edgexfoundry/edgex-taf/issues/218
=> Implement core-metadata PATCH device and GET device

TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot
Fix https://github.com/edgexfoundry/edgex-taf/issues/221
1. convert json string to json for comparison
2. add content-type check
=> Add Content-Type check to v2 app-service trigger tests

TAF/utils/scripts/docker/arm64.env, TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file-perfermance.sh, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/sync-nightly-build.sh, TAF/utils/scripts/docker/x86_64.env
=> Change image url to use dockerhub hanoi release

TAF/testCaseModules/keywords/consul/consul.py
Fix https://github.com/edgexfoundry/edgex-taf/issues/236
=> Add back "modify_consul_config" keyword

TAF/testCaseModules/keywords/consul/consul.py
=> Update consul.py error message

TAF/utils/scripts/docker/docker-compose-end-to-end.yaml
=> Disable App Service Config check

TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot
=> Remove app-service V2 secret testcase from SmokeTest

TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot, TAF/testScenarios/functionalTest/V2-API/core-data/info/GET.robot, TAF/utils/scripts/docker/docker-compose-end-to-end.yaml
Fix https://github.com/edgexfoundry/edgex-taf/issues/245
Also fix the resource path in V2-API/core-data/info/GET.robot
=> Update docker-compose-end-to-end.yaml to remove Vault TLS

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/core-metadata/V2-device/device_data.json, TAF/testData/core-metadata/deviceservice_data.json, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/PATCH-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/DELETE-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/PATCH-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/PATCH-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/POST-Negative.robot
1. Change the following values
- ENABLE > UP
- DISABE < DOWN
2. Remove operatingState from device service
Fix #248 
=> Change operatingState from ENABLE to UP

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot, TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/core-command/coreCommandAPI.robot, TAF/testCaseModules/keywords/core-data/coreDataAPI.robot, TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testCaseModules/keywords/device-sdk/deviceServiceAPI.robot, TAF/testCaseModules/keywords/loggingAPI.robot, TAF/testCaseModules/keywords/support-scheduler/supportSchedulerAPI.robot, TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot, TAF/testScenarios/integrationTest/1_service_operation/1_service_operation.robot, TAF/testScenarios/integrationTest/2_configuration_setting/2_configuration_setting.robot
=> Update keywords from RequestsLibrary

.gitignore, TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/setup/edgex.py, TAF/testCaseModules/keywords/setup/startup_checker.py, TAF/utils/scripts/docker/api-gateway-token.sh
Fix #247
Also, update startup_checker.py to fail deploy testcase if ping services fail
=> Update to use the new Secret Config to generate the new token

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/core-data/coreDataAPI.robot, TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/core-data/readings_data.json, TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/DELETE-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/DELETE-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/PATCH-Positive.robot
=> Update V2 event tests and delete API with id tests

TAF/testCaseModules/keywords/core-data/coreDataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-positive.robot
=> Implement core-data GET and DELETE event V2 API tests

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot, TAF/testData/app-service/secrets_data.json
1. /secrets to /secret
2. property secrets to secretData
=> Update app service secret V2 API tests

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot
=> (Update) Update app service secret V2 API tests

TAF/testCaseModules/keywords/core-data/coreDataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-positive.robot
=> Implement core-data reading V2 API testcases

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot, TAF/testData/app-service/trigger_data.json, TAF/testData/app-service/trigger_response_content.py
=> Update app-service trigger V2 API test data

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot, TAF/testScenarios/functionalTest/V2-API/app-service/info/GET.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot
=> Update app-service-blackbox-tests name to app-service-functional-tests

TAF/utils/scripts/docker/deploy-edgex.sh
=> Update deploy-edgex.sh to startup database before kong

TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/PATCH.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/POST.robot
Add test cases for provision watcher
Fix #278 
=> Add test cases for provision watcher

TAF/config/performance-metrics/configuration.py, TAF/testCaseModules/keywords/performance-metrics-collection/RetrieveFootprint.py
=> Update footprint threshold setting to 1.5 for performance metrics test

TAF/testCaseModules/keywords/core-data/coreDataAPI.robot, TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/core-data/event_data.json, TAF/testData/core-data/readings_data.json, TAF/testData/core-metadata/V2-device/device_data.json, TAF/testData/core-metadata/deviceprofile/Test-Profile-1.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-2.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-3.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-4.yaml, TAF/testData/core-metadata/deviceservice_data.json
POST device profile with upload still failed, will raise an issue for it.
Fix #290
=> Add apiversion to request objects

TAF/testData/core-metadata/deviceprofile/Test-Profile-1.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-2.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-3.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-4.yaml, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Uploadfile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative-UploadFile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Positive.robot
Fix #298
1. Update coreCommands put to set
2. Update deviceResources type to valueType (https://github.com/edgexfoundry/edgex-go/commit/7e47c43b3791a8a423b0f4cf7e6fc0c0a811ab44)
=> Update device profile coreCommands and deviceResources properties

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Positive-II.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/PATCH-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Positive-II.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Uploadfile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/DELETE-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/PATCH-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/POST-Negative.robot
=> Implement Implement core-metadata V2 API testcases with Skipped tags

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot
=> Update core-metadata PATCH V2 API test data to add apiVersion

TAF/testData/app-service/secrets_data.json, TAF/testData/app-service/trigger_data.json
=> Update app-service V2 API test data to add apiVersion

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/DELETE.robot
Implement tests for provision watcher delete method.
issue #291 
=> Implement tests for provision watcher delete method

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/GET-Positive.robot
Implement tests for provision watcher Get method
Fix #291
=> Implement tests for provision watcher Get method

TAF/testData/app-service/trigger_response_content.py
Remove created field for json related string from trigger_response_content.py file
Fix #316
=> Remove created field for json related string

TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/GET-Positive-II.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/PATCH.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/POST.robot
Add robot file for support-notifications subscription
#108
=> Add robot file for support-notifications subscription

TAF/testScenarios/integrationTest/V2-API/core-command/device/GET-Negative.robot, TAF/testScenarios/integrationTest/V2-API/core-command/device/GET-Positive.robot, TAF/testScenarios/integrationTest/V2-API/core-command/device/SET.robot, TAF/testScenarios/integrationTest/V2-API/core-command/info/GET.robot
=> Add Core Command V2 API testcases

TAF/testCaseModules/keywords/core-data/coreDataAPI.robot, TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/app-service/trigger_data.json, TAF/testData/core-data/event_data.json, TAF/testData/core-metadata/V2-device/auto_events_data.json, TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/POST-Negative.robot
=> Update V2 testcases and data to add sourceName to event

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot
Updated ASC Trigger tests to use new function names and set new configuration parameters that have been added.
=> refactor: App Service Trigger tests for function configuration changes

TAF/testData/app-service/trigger_response_content.py
Updated the compared content for AES encryption data.
Fix #326
=> Updated the compare content for AES encryption data

TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
Remove deploy device service on the suite level of integration testing.
Also needs to update smoke test and integration test pipeline script.
=> Remove deploy device service on suite level of integration testing

TAF/testData/app-service/trigger_response_content.py
Updating the trigger_response_content for the changing of sourceName.
Fix #329
=> Updating the trigger_response_content for the changing of sourceName

TAF/testCaseModules/keywords/setup/startup_checker.py
Change pingUrl from v1 to v2.
Fix #332 
=> Change pingUrl from v1 to v2

TAF/utils/scripts/docker/run-tests.sh, docs/run-tests-on-local.md
Update document for deploying device-virtual before running integration-testing
Fix #328 
=> Update document for deploying device-virtual before running integration-testing

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/core-metadata/deviceprofile/Test-Profile-1.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-2.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-3.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-4.yaml, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Uploadfile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative-UploadFile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Positive.robot
=> Update V2 device profile data and testcases to use new model

TAF/config/performance-metrics/configuration.py, TAF/testCaseModules/keywords/performance-metrics-collection/PingResponse.py, TAF/testScenarios/performanceTest/performance-metrics-collection/4_ping_response_time/ping_response_time.robot, TAF/utils/scripts/docker/exec_performance_metrics.sh, docs/run-performance-metrics-collection-on-local.md
- Add a variable to handle the allowable outlier of the ping test.
- Update shell script for variables.
- Update docs for performance metrics collection. 
=> Add a variable to handle the allowable outlier of the ping test

TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot
SetOutputData has been renamed to SetResponseData in PR https://github.com/edgexfoundry/app-service-configurable/pull/214
closes #339
=> refactor: Rename SetOutputData to SetResponseData

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/app-service/trigger_data.json, TAF/testData/app-service/trigger_response_content.py, TAF/testData/core-data/readings_data.json, TAF/testData/core-metadata/V2-device/device_data.json, TAF/testData/core-metadata/deviceprofile/Test-Profile-1.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-2.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-3.yaml, TAF/testData/core-metadata/deviceprofile/Test-Profile-4.yaml, TAF/testData/core-metadata/deviceservice_data.json, TAF/testData/core-metadata/provisionwatcher_data.json, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/PATCH.robot
=> Update V2 test data to remove apiVersion except request, response, and event DTO

TAF/testCaseModules/keywords/support-notifications/subscriptionAPI.robot, TAF/testData/support-notifications/channels_data.json, TAF/testData/support-notifications/subscription_data.json, TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/POST.robot
Implement tests for support-notifications subscription POST method
Fix #324
=> Implement tests for support-notifications subscription POST method

TAF/testCaseModules/keywords/support-notifications/subscriptionAPI.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/GET-Positive-II.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/subscription/GET-Positive.robot
Implement GET method tests for subscription of v2 support-notification
#343
=> Implement GET method tests for subscription of v2 support-notification

TAF/testData/app-service/trigger_response_content.py
Remove created field from app-service trigger data.
Fix #350 
=> Remove created field from app-service trigger data

TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/sync-compose-file.sh
Addresses issue #354
This must be merged so that https://github.com/edgexfoundry/edgex-compose/pull/51 can then pass smoke tests,
=> refactor: Update docker scripts to pull compose files from new location

TAF/config/global_variables.py, TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot, TAF/testScenarios/functionalTest/core-data/UC_readings/add_reading.robot, TAF/testScenarios/integrationTest/1_service_operation/1_service_operation.robot, TAF/testScenarios/integrationTest/2_configuration_setting/2_configuration_setting.robot, TAF/testScenarios/scalabilityTest/modbus/modbus.robot
=> refactor: Switch to 2.0 Consul path

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot
ASC service key pre-fix changed from `AppService-` to `app-`
This ASC PR https://github.com/edgexfoundry/app-service-configurable/pull/229 is waiting on this PR.
=> refactor: Update App Service tests for change in service key

TAF/testCaseModules/keywords/support-scheduler/supportSchedulerAPI.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/info/GET.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/GET.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/PATCH.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/POST.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/GET.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/PATCH-Negative.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/PATCH-Positive.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/POST-Positive.robot
Create test cases for support-scheduler API
Fix #110 #111 
=> Create test cases for support-scheduler API

TAF/config/device-virtual/configuration.toml, TAF/testCaseModules/keywords/device-sdk/deviceServiceAPI.robot, TAF/testScenarios/functionalTest/device-service/common/3_device_profile/3_device_profile.robot, TAF/testScenarios/functionalTest/device-service/common/4_device/4_device.robot, TAF/testScenarios/functionalTest/device-service/common/5_query_commands/5_query_commands.robot, TAF/testScenarios/functionalTest/device-service/common/7_actuation_commands/7_actuation_commands.robot, TAF/testScenarios/functionalTest/device-service/common/discovery/POST.robot, TAF/testScenarios/functionalTest/device-service/common/info/GET.robot
1. Implement tests for device-sdk API.
2. Update configuration.toml to the latest.
Fix #360 
=> Implement tests for device-sdk API

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/support-scheduler/supportSchedulerAPI.robot, TAF/testData/support-scheduler/interval.json, TAF/testData/support-scheduler/interval_action.json, TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
Modify integration-test to use v2 API.
Fix #369 
=> Modify integration-test to use v2 API

TAF/testCaseModules/keywords/support-scheduler/supportSchedulerAPI.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/POST.robot
Implement interval tests for support-scheduler POST method.
#379 POST method
=> Implement interval tests for support-scheduler POST method

TAF/testCaseModules/keywords/support-scheduler/supportSchedulerAPI.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/DELETE.robot
Implement interval tests for support-scheduler Delete method
#379 DELETE method
=> Implement interval tests for support-scheduler Delete method

TAF/testCaseModules/keywords/support-scheduler/supportSchedulerAPI.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/GET.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/PATCH.robot
Implement interval tests for support-scheduler PATCH and GET methods.
Fix #379 PATCH and GET methods.
=> Implement interval tests for support-scheduler PATCH and GET methods

TAF/testCaseModules/keywords/support-scheduler/supportSchedulerAPI.robot, TAF/testData/support-scheduler/interval_action.json, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/GET.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/PATCH.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/POST-Positive.robot, TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot
=> Implement scheduler intervalAction V2 POST, DELETE API tests

TAF/testCaseModules/keywords/support-scheduler/supportSchedulerAPI.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/GET.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/PATCH-Negative.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/PATCH-Positive.robot
=> Implement scheduler intervalAction V2 GET, PATCH API tests

TAF/utils/scripts/docker/get-compose-file.sh
Update the replace keyword for device-modbus.
Fix #389 
=> Update the replace keyword for device-modbus

TAF/utils/scripts/docker/api-gateway-token.sh
Updated the script to utilize the new features of the security config application to use the JWT when creating/removing users within the Kong gateway and creating/associating a JWT to that user. 
Fixes: #395
=> fix: Update gateway token generation

TAF/config/default/configuration.py, TAF/config/device-modbus/configuration.py, TAF/config/device-virtual/configuration.py, TAF/config/global_variables.py
=> refactor: Change gateway port to 8100

TAF/config/default/configuration.py, TAF/config/device-modbus/configuration.py, TAF/config/device-virtual/configuration.py, TAF/config/global_variables.py
Reverts edgexfoundry/edgex-taf#398
=> Revert "refactor: Change gateway port to 8100"

TAF/utils/scripts/docker/deploy-edgex.sh
=> refactor: Change delpoy-edgex.sh to deploy all security services together

TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/GET.robot
Add scheduler tests to SmokeTest for the kong issue.
=> Add scheduler tests to SmokeTest for kong issue

TAF/testScenarios/functionalTest/V2-API/core-command/device/GET-Positive.robot
=> Add parameters check for core-command V2 API testcases

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Positive-II.robot
=> Add query device resource testcases for core-metadata new V2 API

TAF/testCaseModules/keywords/system-agent/systemAgentAPI.robot
=> Fix system agent url to use http

TAF/config/device-modbus/sample_profile.yaml, TAF/utils/scripts/docker/exec_performance_metrics.sh, TAF/utils/scripts/docker/run-tests.sh, docs/modbus-scalability-test.md
1. Update startingAddress to zero-based value
2. Remove the docker- prefix on taf-common image.
Fix #417
=> Update startingAddress to zero-based value

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testCaseModules/keywords/support-notifications/subscriptionAPI.robot, TAF/testCaseModules/keywords/support-scheduler/supportSchedulerAPI.robot, TAF/testData/core-metadata/auto_events_data.json, TAF/testData/support-scheduler/interval.json, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/PATCH.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/PATCH.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/POST.robot, TAF/testScenarios/functionalTest/device-service/common/6_scheduling/6_scheduling.robot, TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot
=> Rename frequency to interval for auto-events and scheduler interval

TAF/config/default/configuration.toml, TAF/config/device-modbus/configuration.py, TAF/config/device-modbus/configuration.toml, TAF/config/device-virtual/configuration.toml, TAF/config/modbus_scalability_test/configuration.py, TAF/config/modbus_scalability_test/configuration.toml, TAF/testData/core-metadata/device_protocol.json, TAF/testScenarios/functionalTest/core-data/UC_readings/add_reading.robot, TAF/testScenarios/scalabilityTest/modbus/modbus.robot, TAF/utils/scripts/docker/get-compose-file.sh, docs/edgex-taf.md, docs/modbus-scalability-test.md
=> refactor: Update for service key name changes to remove edgex- prefix

TAF/utils/scripts/docker/api-gateway-token.sh
=> fix: Update service key name in token path to new name

TAF/testScenarios/integrationTest/UC_kuiper/export_by_kuiper_rules.robot
Add test cases for Kuiper integration-test
#231
=> Add test cases for kuiper integration-test

TAF/config/device-modbus/configuration.py, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
Handling long string in mqtt-subscriber data and update device-modbus proxy route url.
Fix #432 
=> Handling long string in mqtt-subscriber data

TAF/config/device-virtual/configuration.toml
Update device-virtual's configuration.toml.
Fix #434 
=> Update device-virtual's configuration.toml

TAF/testScenarios/functionalTest/V2-API/support-notifications/cleanup/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Negative-II.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Positive-II.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Positive.robot
Add test cases for Support-Notifications transmission and cleanup
Fix #108 #109
=> Add test cases for Support-Notifications transmission and cleanup

TAF/utils/scripts/docker/deploy-edgex.sh
=> Extend the waiting time before running the test scripts

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/support-notifications/cleanupAPI.robot, TAF/testCaseModules/keywords/support-notifications/notificationAPI.robot, TAF/testCaseModules/keywords/support-notifications/transmissionAPI.robot, TAF/testData/support-notifications/notification_data.json, TAF/testScenarios/functionalTest/V2-API/support-notifications/cleanup/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/info/GET.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/notification/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/notification/POST.robot
=> Implement Info, cleanup, and post/delete notification V2 API tests

TAF/testCaseModules/keywords/support-notifications/notificationAPI.robot, TAF/testCaseModules/keywords/support-notifications/subscriptionAPI.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/notification/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/notification/GET-Negative-II.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/notification/GET-Negative-III.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/notification/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/notification/GET-Positive-II.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/notification/GET-Positive.robot
=> Implement support-notifications GET V2 API tests

TAF/testData/app-service/secrets_data.json, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
1. Create secret for app-service-http-export service.
2. Update validation data for app-service-http-export service.
Fix #455 
=> Create secret for app-service-http-export service

TAF/testCaseModules/keywords/setup/startup_checker.py, TAF/testCaseModules/keywords/system-agent/systemAgentAPI.robot, TAF/testScenarios/functionalTest/V2-API/system-agent/services/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/system-agent/services/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Positive.robot, TAF/utils/scripts/docker/get-compose-file.sh
=> Implement sys-mgmt-agent V2 API tests

TAF/config/global_variables.py, TAF/testCaseModules/keywords/support-notifications/subscriptionAPI.robot, TAF/testCaseModules/keywords/support-notifications/transmissionAPI.robot, TAF/testData/support-notifications/channels_data.json, TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/DELETE.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Negative-II.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Positive-II.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Positive.robot
Implement tests of GET and DELETE transmission API for support-notifications.
Fix #451
=> Implement tests of GET and DELETE transmission API

TAF/testCaseModules/keywords/support-scheduler/supportSchedulerAPI.robot, TAF/testData/support-scheduler/interval.json, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/PATCH.robot
=> Remove runOnce field

TAF/testCaseModules/keywords/setup/startup_checker.py, TAF/testScenarios/functionalTest/V2-API/system-agent/services/GET-Negative.robot, TAF/testScenarios/functionalTest/V2-API/system-agent/services/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Positive.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
=> Remove 'edgex-' from container name on SMA tests

TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Positive.robot, TAF/utils/scripts/docker/deploy-edgex.sh
Add sleep time after restarting device-rest on SysMgmtPOST003.
Fix #469
=> Add sleep time after restarting device-rest on SysMgmtPOST003

.github/semantic.yml
=> build: add semantic.yml for conventional commits

TAF/testScenarios/integrationTest/UC_metadata_notifications/metadata_notifications
=> Create support-notifications integration test cases

TAF/testCaseModules/keywords/core-command/coreCommandAPI.robot, TAF/testCaseModules/keywords/device-sdk/deviceServiceAPI.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_false.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_true.robot, TAF/utils/src/setup/redis-subscriber.py
=> feat: Implement tests for device-service of integration-test

TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-negative.robot
=> feat: Add core-data Writable.PersistData testcase

TAF/testCaseModules/keywords/device-sdk/deviceServiceAPI.robot
=> fix: redis subscriber on arm64 didn't receive data

TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
Based on #211, writing the related scenarios.
=> feat: Add store and forward capability test cases

TAF/testScenarios/performanceTest/performance-metrics-collection/4_ping_response_time/ping_response_time.robot
=> feat: Eliminate Max and min values for performance ping test

TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot, TAF/utils/scripts/docker/restart-services.sh
=> feat: Implement store and forward capability test for integration test

TAF/config/global_variables.py, TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
=> fix: Remove sleep time before restarting app-service when running tests on arm64

TAF/testCaseModules/keywords/performance-metrics-collection/EventExportedTime.py
=> feat: Eliminate the max and min exported time for performance tests

TAF/testCaseModules/keywords/core-data/coreDataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-negative-II.robot, TAF/testScenarios/functionalTest/V2-API/core-data/reading/GET-positive-II.robot
=> feat: Add core-data V2 API test GET reading by resource and device

TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Positive-II.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/interval/PATCH.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/GET.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/POST-Positive.robot
=> feat: Implement config tests for support services

TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/POST-Positive.robot
=> fix: Add AdminState into pre-created intervalaction

TAF/config/device-virtual/sample_profile.yaml, TAF/testCaseModules/keywords/device-sdk/deviceServiceAPI.robot, TAF/testScenarios/integrationTest/UC_device_service/device_configuration.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_false.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_true.robot
Add tests for the following configurations.
#510
- MessageQueue.PublishTopicPrefix (redis message bus)
- Device.DataTransform
- Device.UpdateLastConnected
=> feat: Implement device config test for device-virtual

TAF/testScenarios/deploy.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/sync-compose-file.sh
- Get mqtt-bus compose file when running integration-test and executing get-compose-file.sh.
- Removed unused variables `USE_DB` and `USE_RELEASE` in shell scripts.
- Removed scripts which is unused after Hanoi release.
Fix #517
=> feat: Implement mqtt bus tests for device-virtual

TAF/testCaseModules/keywords/core-data/coreDataAPI.robot, TAF/testCaseModules/keywords/device-sdk/deviceServiceAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_false.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_true.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot
=> feat: Implement config tests for core-data

TAF/config/device-virtual/sample_profile.yaml
=> fix: Update sample profile to remove write binary resources

TAF/testScenarios/functionalTest/V2-API/core-command/device/GET-Positive.robot
=> fix: update core-command testcase to use binary read command

TAF/testScenarios/integrationTest/UC_metadata_notifications/metadata_notifications.robot
=> fix: Set Core-Metadata PostDeviceChanges=true for integrationTest

TAF/utils/scripts/docker/deploy-edgex.sh
Add for loop to check proxy setup container status after deployment.
Fix #544.
=> fix: Waiting for proxy setup ready on security test

TAF/testScenarios/functionalTest/V2-API/core-command/device/GET-Negative.robot
=> feat: Add core-command "Get unavailable device read command" testcase

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testScenarios/functionalTest/V2-API/core-command/device/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Positive-II.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/device/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Positive-II.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceservice/GET-Positive.robot
=> fix: update core-command and core-metadata count check keyword

TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot, TAF/utils/scripts/docker/get-compose-file.sh
=> feat: Add testcases for MQTT messageQueue QoS configuration

TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/POST-Positive.robot
Add ping request to waiting for starting scheduler
Fix #553 
=> Add ping request to waiting for starting scheduler

TAF/testData/kuiper/stream.json
=> fix: Update kuiper tests to use shared stream

TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
=> fix: Update StoreAndForward005 to correctly get retry log

TAF/utils/scripts/docker/common-taf.env, TAF/utils/scripts/docker/exec_performance_metrics.sh, TAF/utils/scripts/docker/get-compose-file-perfermance.sh, TAF/utils/scripts/docker/get-compose-file.sh
1. Replace MQTT_BROKER_IP with MQTT_BROKER_HOSTNAME
2. Update performance compose branch name
Fix #605 
=> fix: Replace MQTT_BROKER_IP with MQTT_BROKER_HOSTNAME

TAF/utils/scripts/docker/deploy-edgex.sh
Read environment variable file when executing performance-test
#605
=> fix: Read environment variable file when executing performance-test

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Uploadfile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive.robot
=> feat: Update funcationalTest V2-API deviceprofile tests for empty deviceResources

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Negative-Basicinfo.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Positive-Basicinfo.robot
=> feat: Add PATCH deviceprofile basicinfo tests

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/setup/edgex.py, TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot, TAF/testScenarios/functionalTest/V2-API/support-scheduler/intervalaction/POST-Positive.robot, TAF/testScenarios/functionalTest/V2-API/system-agent/services/POST-Positive.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot, TAF/utils/scripts/docker/execute-command-in-docker.sh, TAF/utils/scripts/docker/query-docker-logs.sh, TAF/utils/scripts/docker/remove-services.sh, TAF/utils/scripts/docker/stop-services.sh
=> fix: Move docker command under utils/scripts directory

TAF/testData/app-service/trigger_response_content.py, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Negative-Basicinfo.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Positive-Basicinfo.robot
fix #633 and skipped unimplement testcase.
=> fix: Add units to app-service XML response-content

TAF/testData/kuiper/action.json, TAF/testScenarios/integrationTest/UC_kuiper/export_by_kuiper_rules.robot, TAF/utils/src/setup/mqtt-subscriber.py, TAF/utils/src/setup/redis-subscriber.py
=> feat: Run integrationTest kuiper test with MQTT MessageBus

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative-DeviceResource.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Positive-DeviceResource.robot
=> feat: Add DELETE device resource test

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Negative-Deviceresource.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Positive-Deviceresource.robot
=> feat: Add PATCH deviceResource tests

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative-UploadFile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative.robot
close #640
Run functionalTest with non-security and security, and all tests pass.
=> feat: Add metadata testcases for ProfileChange configs

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Deviceresource.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-Deviceresource.robot
=> feat: Add POST device resource tests

TAF/config/default/sample_profile.yaml, TAF/config/device-virtual/sample_profile.yaml, TAF/testScenarios/integrationTest/UC_device_service/device_configuration.robot
close #654
Run integration test with docker, and all testcases pass.
=> feat: Add device service ReadingUnits config tests

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-DeviceCommand.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-DeviceCommand.robot
=> feat: Add POST deviceCommand tests

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Negative-DeviceCommand.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/DELETE-Positive-DeviceCommand.robot
=> feat: Add DELETE device command tests

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Negative-DeviceCommand.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Positive-DeviceCommand.robot
=> feat(core-metadata): Add PATCH deviceCommand tests

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Negative-Basicinfo.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Positive-Basicinfo.robot
=> feat: Implement testcase for PATCH basic info

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Negative-DeviceCommand.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Positive-DeviceCommand.robot
=> feat: Implement PATCH device command

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/core-metadata/resource_profile.json, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Deviceresource.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-Deviceresource.robot
=>  feat: Implement test for POST resource

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/core-metadata/command_profile.json, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-DeviceCommand.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-DeviceCommand.robot
=> feat: Implement POST device command

TAF/utils/scripts/docker/exec_performance_metrics.sh, TAF/utils/scripts/docker/get-compose-file-perfermance.sh, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/run-tests.sh, docs/run-tests-on-local.md
=> feat: Set kamakura release images to default test images

TAF/utils/scripts/docker/run-tests.sh, docs/run-tests-on-local.md
=> fix: Update main branch to pull the correct image

TAF/utils/scripts/docker/run-tests.sh
=> fix: Update run-tests.sh for the jakarta branch

TAF/utils/scripts/docker/run-tests.sh
=> fix: Update run-tests.sh for the kamakura branch

TAF/utils/scripts/docker/run-tests.sh
=> fix: Update run-tests.sh for the main branch

TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot
close #686 
Signed-off-by: jumpingliu <melody@iotechsys.com>
=> fix: remove log validation on integration-test

TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
close #691
Signed-off-by: jumpingliu <melody@iotechsys.com>
=> Fix: add kill process step in the StoreAndForward001

TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot
Validate the content variable should not be empty.
Fix #699 
=> fix: Script validation error in core-data-config tests

TAF/testData/app-service/secrets_data.json, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot, TAF/utils/src/setup/aes256-decrypt.py
Fix #541 implement decrypt validation
=> feat: Update ASC functional tests to use new aes256 Encrypt algorithm

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Negative-Deviceresource.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PATCH-Positive-Deviceresource.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Deviceresource.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative-Uploadfile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive-Deviceresource.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/POST-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative-UploadFile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/info/GET.robot
#684 This PR only add test scenarios, and the tests will be implemented on next PR.
=> feat: Test Scenarios for Units of Measure(UoM)

TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot
=> fix: update script for Store And Forward test cases

TAF/testScenarios/performanceTest/performance-metrics-collection/2_service_startup_time/service_startup_time.robot, TAF/utils/scripts/docker/deploy-device-service.sh, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/deploy-services.sh, TAF/utils/scripts/docker/exec_performance_metrics.sh, TAF/utils/scripts/docker/remove-services.sh, TAF/utils/scripts/docker/restart-services.sh, TAF/utils/scripts/docker/run-tests.sh, TAF/utils/scripts/docker/shutdown.sh, TAF/utils/scripts/docker/stop-services.sh
1. Add compose v2 command `docker compose`, it is required by image `docker:20.10.18`
2. Assign valid CONF_DIR value which is required by compose v2
Fix #702
=> feat: Use Compose V2 to run test

TAF/testScenarios/integrationTest/UC_delayed_start/delayed_start_services.robot, TAF/utils/scripts/docker/get-compose-file.sh
1. Ping APIs always send for checking services are startup.
2. Add a test to check the delayed start services get token from spiffe-token-provider.
=> feat: Generate compose file for Delayed Start test

TAF/testScenarios/integrationTest/UC_system_events/metadata_system_events.robot
According to [system-events docs](https://docs.edgexfoundry.org/2.3/microservices/core/metadata/Ch-Metadata/#device-system-events),
test scenarios is based on the difference of topic subscribed from mosquitto.
=> feat: test scenarios for core-metadata system events

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot, TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/common/metrics.robot, TAF/testCaseModules/keywords/performance-metrics-collection/EventExportedTime.py, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-positive.robot, TAF/testScenarios/functionalTest/V2-API/support-notifications/transmission/GET-Positive.robot, TAF/testScenarios/integrationTest/UC_app_service_configurable/external_mqtt_trigger.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot, TAF/testScenarios/integrationTest/UC_kuiper/export_by_kuiper_rules.robot, TAF/testScenarios/integrationTest/UC_metadata_notifications/metadata_notifications.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_mqtt.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_redis.robot, TAF/testScenarios/integrationTest/UC_metrics/core_data_metrics_mqtt.robot, TAF/testScenarios/integrationTest/UC_metrics/core_data_metrics_redis.robot, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/src/setup/mqtt-publisher.py, TAF/utils/src/setup/mqtt-subscriber.py, TAF/utils/src/setup/redis-publisher.py
=> feat: Implement tests for app service metrics

TAF/utils/scripts/docker/get-compose-file.sh
=> fix: Update sed command to not use the hard code keyword to retreive device services

TAF/testScenarios/integrationTest/UC_north_south_messaging/GET-Negative.robot, TAF/testScenarios/integrationTest/UC_north_south_messaging/GET-Positive.robot, TAF/testScenarios/integrationTest/UC_north_south_messaging/SET.robot
=> feat: Add test scenarios for North-South Messaging

TAF/config/performance-metrics/configuration.py, TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/common/metrics.robot, TAF/testCaseModules/keywords/performance-metrics-collection/EventExportedTime.py, TAF/testScenarios/integrationTest/UC_app_service_configurable/external_mqtt_trigger.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot, TAF/testScenarios/integrationTest/UC_kuiper/export_by_kuiper_rules.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_mqtt.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_redis.robot, TAF/utils/src/setup/mqtt-subscriber.py, TAF/utils/src/setup/redis-subscriber.py
Update mqtt/redis subscribe script for handling messages.
=> fix: Handle mlutiple messages for subscriber script

TAF/testScenarios/integrationTest/UC_system_events/metadata_system_events_redis.robot
=> feat: [redis bus]implement test for system events

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/common/metrics.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_false.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_true.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_mqtt.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_redis.robot, TAF/testScenarios/integrationTest/UC_metrics/core_data_metrics_mqtt.robot, TAF/testScenarios/integrationTest/UC_metrics/core_data_metrics_redis.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot, TAF/testScenarios/integrationTest/UC_system_events/metadata_system_events_mqtt.robot, TAF/testScenarios/integrationTest/UC_system_events/metadata_system_events_redis.robot, TAF/utils/scripts/docker/common-taf.env, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/src/setup/mqtt-publisher.py
1. Use host.docker.internal for docker host ip
2. Replace Terminate All Processes with Terminate Process - `Terminate All Processes` seems not work everytime
3. Add missing libraries for mqtt publish script
Fix #725
Fix #726
=> fix: Use host.docker.internal for docker host ip

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/core-command/externalSystem.robot, TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/core-command/north_south_messaging.json, TAF/testScenarios/functionalTest/V2-API/core-command/device/GET-Negative.robot, TAF/testScenarios/integrationTest/UC_north_south_messaging/GET-Negative.robot, TAF/testScenarios/integrationTest/UC_north_south_messaging/GET-Positive.robot, TAF/testScenarios/integrationTest/UC_north_south_messaging/SET.robot, TAF/utils/scripts/docker/get-compose-file.sh
=> feat: Implement tests for North-South Messaging

TAF/testScenarios/functionalTest/V2-API/core-command/device/GET-Negative.robot
Error caused by the script update from PR #728.
=> fix: update script to create unavailable modbus device

TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file.sh
=> fix: Restrict Jakarta branch when updating MQTT broker Url

TAF/testCaseModules/keywords/device-sdk/deviceServiceAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-command/device/GET-Negative.robot, TAF/testScenarios/integrationTest/UC_north_south_messaging/GET-Negative.robot
=> fix: Update script to unavailable modbus device for ErrNSMessagingGET012

TAF/utils/scripts/docker/exec_performance_metrics.sh, TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file-perfermance.sh, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/run-bct-test.sh, TAF/utils/scripts/docker/run-tests.sh, docs/run-tests-on-local.md
=> fix: Update default value of USE_SHA1 to levski

TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot, TAF/testScenarios/integrationTest/UC_kuiper/export_by_kuiper_rules.robot, TAF/testScenarios/integrationTest/UC_north_south_messaging/GET-Positive.robot
1. Remove unused tags
2. Add smoke-test case for mqtt bus
=> fix: Add smoke-test case for mqtt bus

TAF/utils/scripts/docker/deploy-device-service.sh, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/deploy-services.sh, TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/remove-services.sh, TAF/utils/scripts/docker/restart-services.sh, TAF/utils/scripts/docker/run-bct-test.sh, TAF/utils/scripts/docker/shutdown.sh, TAF/utils/scripts/docker/stop-services.sh, docs/edgex-taf.md, docs/run-tests-on-local.md
=> refactor: Rename CONF_DIR_PLACE_HOLDER to CONFIG_DIR_PLACE_HOLDER

TAF/utils/scripts/docker/get-compose-file.sh
=> refactor: Remove command for enabling mqtt-broker verbose mode

TAF/config/modbus_scalability_test/configuration.toml, TAF/testScenarios/integrationTest/UC_app_service_configurable/external_mqtt_trigger.robot, TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot, TAF/testScenarios/integrationTest/UC_device_service/device_configuration.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_false.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_true.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot, TAF/testScenarios/integrationTest/UC_kuiper/export_by_kuiper_rules.robot, TAF/testScenarios/integrationTest/UC_metadata_notifications/metadata_notifications.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_mqtt.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_redis.robot, TAF/testScenarios/integrationTest/UC_metrics/core_data_metrics_mqtt.robot, TAF/testScenarios/integrationTest/UC_metrics/core_data_metrics_redis.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot, TAF/testScenarios/integrationTest/UC_north_south_messaging/GET-Negative.robot, TAF/testScenarios/integrationTest/UC_north_south_messaging/GET-Positive.robot, TAF/testScenarios/integrationTest/UC_north_south_messaging/SET.robot, TAF/testScenarios/integrationTest/UC_system_events/metadata_system_events_mqtt.robot, TAF/testScenarios/integrationTest/UC_system_events/metadata_system_events_redis.robot, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/run-bct-test.sh, TAF/utils/scripts/docker/run-tests.sh, TAF/utils/scripts/snap/run-tests.sh
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
=> refactor: Adjust TAF scripts for changes to MessageBus configuration

TAF/utils/scripts/docker/get-compose-file.sh
=> fix: refractor volumes for Delay Start services

TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot, TAF/utils/scripts/snap/snap-utils.sh
Signed-off-by: Leonard Goodell <leonard.goodell@intel.com>
=> refactor: Adjust snap utils  and tests for MessageBus config changes and remaining message queue references

TAF/testData/core-command/north_south_messaging.json, TAF/testScenarios/functionalTest/V2-API/core-command/device/GET-Positive.robot, TAF/testScenarios/functionalTest/device-service/common/5_query_commands/5_query_commands.robot, TAF/testScenarios/integrationTest/UC_data_clean_up/clean_up_events_and_readings.robot, TAF/testScenarios/integrationTest/UC_device_service/device_configuration.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_false.robot, TAF/testScenarios/integrationTest/UC_device_service/messagebus_true.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_store_forward.robot, TAF/testScenarios/integrationTest/UC_kuiper/export_by_kuiper_rules.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_mqtt.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_redis.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot, TAF/testScenarios/integrationTest/UC_north_south_messaging/GET-Positive.robot
=> refactor: ds-pushevent and ds-returnevent to use true/false instead of yes/no

TAF/utils/scripts/docker/get-compose-file.sh
Fix for changes from this PR : https://github.com/edgexfoundry/edgex-go/pull/4275
=> refactor: Rename MESSAGEBUS_INTERNAL to EXTERNALMQTT

TAF/testScenarios/functionalTest/V2-API/app-service/trigger/POST-negative.robot
=> refactor: Replace UseTargetTypeOfByteArray with TargetType

TAF/testCaseModules/keywords/app-service/AppServiceAPI.robot, TAF/testData/app-service/secrets_data.json, TAF/testScenarios/functionalTest/V2-API/app-service/secrets/POST.robot
=> refactor: Rename path to secretName for secret API

TAF/testCaseModules/keywords/core-data/coreDataAPI.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/DELETE-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/GET-positive.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-negative.robot, TAF/testScenarios/functionalTest/V2-API/core-data/event/POST-positive.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot
=> refactor: Add serviceName parameter on Post Event API

TAF/config/modbus_scalability_test/configuration.toml, TAF/testScenarios/integrationTest/UC_device_service/device_configuration.robot
Since the LastConnected field was removed by go-mod-core-contracts. Remove the related tests.
Close #783
=> feat!: Remove LastConnected related tests

TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative-UploadFile.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/deviceprofile/PUT-Positive.robot, docs/run-tests-on-local.md
Update script to check whether the units field is exist.
Close #787
Run edgex-taf function test with latest edgex images.
=> fix: Update Profile PUT test case to check non-existent field 

TAF/utils/scripts/docker/api-gateway-token.sh, TAF/utils/scripts/snap/api-gateway-token.sh
=> fix: Use EdgeX 3.0 method to get API gateway token

TAF/testScenarios/integrationTest/UC_device_service/new_source_commands.robot
=> feat: Add tests for new resource and command

TAF/config/device-modbus/sample_profile.yaml, TAF/config/device-virtual/sample_profile.yaml, TAF/utils/scripts/docker/deploy-edgex.sh
=> fix: Update data type of resource properties and update deploy validation when security enabled

TAF/utils/scripts/docker/get-compose-file-perfermance.sh
=> fix: Update ADD_PROXY_ROUTE for performance test

TAF/testCaseModules/keywords/core-command/externalSystem.robot, TAF/utils/scripts/docker/get-compose-file-backward.sh, TAF/utils/scripts/docker/get-compose-file.sh
=> refactor: Update compared ReceivedTopic value for north-south-messaging

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/core-metadata/provisionwatcher_data.json, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/GET-Positive.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/PATCH.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/POST-Negative.robot, TAF/testScenarios/functionalTest/V2-API/core-metadata/provisionwatcher/POST-Positive.robot
=> refactor: Update provision watcher to support new DTO

TAF/testCaseModules/keywords/core-command/externalSystem.robot, TAF/testScenarios/integrationTest/UC_kuiper/export_by_kuiper_rules.robot, TAF/utils/scripts/docker/get-compose-file.sh
Closes #824 
1. Correct ReceivedTopic value
2. Fix delayed-start error
3. Skip Kuiper test on security test
=> refactor: Correct ReceivedTopic value

TAF/config/default/sample_profile.yaml, TAF/config/device-modbus/sample_profile.yaml, TAF/config/device-virtual/sample_profile.yaml, TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/common/metrics.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_mqtt.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_redis.robot
Closes #826
Also fix:
Correct Topics value of PerTopicPipeline from `edgex/events/device/#/${device_name}/#` to `edgex/events/device/+/+/${device_name}/#`
=> refactor: Update the minimum and maximum value to avoid convering int64/uint64 to float64 limitation

TAF/utils/scripts/docker/get-compose-file-perfermance.sh
=> refactor: Replace ADD_PROXY_ROUTE with EDGEX_ADD_PROXY_ROUTE

TAF/testCaseModules/keywords/performance-metrics-collection/PingResponse.py, TAF/testData/app-service/trigger_response_content.py
Closes #838 
Also removed the unused trigger content.
=> fix: Update trigger_content to use api version v3

TAF/testCaseModules/keywords/core-metadata/coreMetadataAPI.robot, TAF/testData/core-metadata/provisionwatcher_data.json, TAF/testScenarios/functionalTest/API/core-metadata/provisionwatcher/GET-Positive.robot, TAF/testScenarios/functionalTest/API/core-metadata/provisionwatcher/PATCH.robot, TAF/testScenarios/functionalTest/API/core-metadata/provisionwatcher/POST-Negative.robot, TAF/testScenarios/functionalTest/API/core-metadata/provisionwatcher/POST-Positive.robot
=> refactor: Move serviceName out of discoveredDevice for provision watcher tests

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testScenarios/functionalTest/API/app-service/secrets/POST.robot, TAF/testScenarios/functionalTest/API/support-notifications/secrets/POST.robot, TAF/testScenarios/functionalTest/device-service/common/secrets/POST.robot
=> fix: Secret stored to consul in non-secure mode

README.md
=> docs: Remove extra wording from the last commit

TAF/testCaseModules/keywords/performance-metrics-collection/RetrieveResourceUsage.py
=> fix: Add logger for memory calculation of performance metrics test

TAF/testScenarios/integrationTest/UC_CORS_configuration/cors_configuration.robot
#850 
Add tests for CORS Configuration and skip when security enabled.
=> feat: Add tests for CORS Configuration

TAF/config/device-modbus_1/configuration.py, TAF/testData/core-metadata/device_protocol.json, TAF/testScenarios/integrationTest/UC_device_service/multiple_instances.robot, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/get-compose-file.sh
=> feat: add tests for multiple instances of device-service

TAF/config/global_variables.py, TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testData/all-services/secrets_data.json, TAF/testData/httpd/device.json, TAF/testData/httpd/profile.json, TAF/testData/httpd/provisionwatcher.json, TAF/testScenarios/integrationTest/UC_URI_for_files/URI_for_files.robot, TAF/utils/scripts/docker/common-taf.env, TAF/utils/scripts/docker/get-compose-file.sh, TAF/utils/scripts/docker/get-uri-test-files.sh, TAF/utils/scripts/docker/httpd/htaccess, TAF/utils/scripts/docker/httpd/htpasswd, TAF/utils/scripts/docker/httpd/httpd-vhosts.conf, TAF/utils/scripts/docker/httpd/httpd.conf, TAF/utils/scripts/docker/httpd/tools_yaml
=> feat: Add test for URI for files

TAF/testCaseModules/keywords/common/commonKeywords.robot, TAF/testCaseModules/keywords/core-command/externalSystem.robot, TAF/testScenarios/functionalTest/API/app-service/trigger/POST-positive.robot, TAF/testScenarios/functionalTest/API/support-scheduler/intervalaction/POST-Positive.robot, TAF/testScenarios/integrationTest/UC_app_service_configurable/external_mqtt_trigger.robot, TAF/testScenarios/integrationTest/UC_delayed_start/delayed_start_services.robot, TAF/testScenarios/integrationTest/UC_end_to_end/export_data_to_backend.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_mqtt.robot, TAF/testScenarios/integrationTest/UC_metrics/app_services_metrics_redis.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/core_data_config.robot, TAF/testScenarios/integrationTest/UC_mqtt_message_bus/device_virtual_config.robot, TAF/testScenarios/performanceTest/performance-metrics-collection/2_service_startup_time/service_startup_time.robot
=> fix: Add timeout in Run Process keyword and increase retry time for failure tests

TAF/utils/scripts/docker/deploy-device-service.sh, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/exec_performance_metrics.sh, TAF/utils/scripts/docker/remove-services.sh, TAF/utils/scripts/docker/run-bct-test.sh, TAF/utils/scripts/docker/run-tests.sh, TAF/utils/scripts/docker/stop-services.sh, docs/run-tests-on-local.md
`docker:26.0.1` image uses `compose version 2.26.1`
=> fix: Upgrade compose version 2.26.1

TAF/utils/scripts/docker/deploy-device-service.sh, TAF/utils/scripts/docker/deploy-edgex.sh, TAF/utils/scripts/docker/exec_performance_metrics.sh, TAF/utils/scripts/docker/remove-services.sh, TAF/utils/scripts/docker/run-bct-test.sh, TAF/utils/scripts/docker/run-tests.sh, TAF/utils/scripts/docker/shutdown.sh, TAF/utils/scripts/docker/stop-services.sh, docs/run-tests-on-local.md
=> fix(napa): Upgrade compose version 2.26.1

TAF/testScenarios/integrationTest/UC_north_south_messaging/GET-Positive.robot
Display message payload before checking the error code.
Run the tests to inspect the message payload.
=> feat: Display message payload

TAF/testCaseModules/keywords/scalabilityTest/modbus/run.py, TAF/utils/src/setup/mqtt-publisher.py, TAF/utils/src/setup/mqtt-subscriber.py
relate to https://github.com/edgexfoundry/edgex-taf-common/pull/120
=> build: paho-mqtt V1 to V2 migration

TAF/config/global_variables.py, TAF/testCaseModules/keywords/performance-metrics-collection/EventExportedTime.py, TAF/utils/scripts/docker/run-tests.sh
Close #953 
- Update variable Release Version to 4.1
- Update integration-test in run-tests.sh.
- Update subscriber_logs in EventExportedTime.py
=> fix: Update Release Version to 4.1

TAF/testScenarios/integrationTest/UC_core_metadata_configurable/core_metadata_configurable.robot
#935 
Not applicable yet. Only test scenarios are drafted, implementation pending.
Not applicable yet. Only test scenarios are drafted, implementation pending.
=> feat: Add integration test scenarios for Device and Resource limit

TAF/testScenarios/integrationTest/UC_core_metadata_configurable/core_metadata_configurable.robot
Closed #935
This PR adds integration test cases to verify the behavior of the Core Metadata service when MaxDevices and MaxResources constraints are applied.
=> feat: Implement integration test for max device and resource configs

TAF/testScenarios/integrationTest/UC_ACL/acl.robot
#932 
(N/A – this PR only adds test scenario)
=> feat: Add integration test scenarios for external JWT
